# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if present
      env:
        CI: true
    
  
  generate-index-d-ts:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: guahanweb/action-nodejs-gh-pages@1.0.0
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: node app.js
      env:
        CI: true
    - name: Set git config and add changes
      run: |
          git config --global user.email "${GITHUB_ACTOR}@https://users.noreply.github.com/"
          git config --global user.name "${GITHUB_ACTOR}"
          git add --all
    - name: push diff
      run: |
          COMMIT_MESSAGE="gen index.d.ts on $(date +'%Y-%m-%d %H:%M:%S')" 
          git commit -m "$(COMMIT_MESSAGE)" 
          git push   
      
